name: Deploy to Cloudflare R2

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to dist
        run: |
          rm -rf ./dist
          mkdir -p ./dist
          rsync -a --exclude='.git' --exclude='.github' --exclude='dist' . ./dist/
      - name: Delete existing folder on R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          aws s3 rm s3://${{ secrets.R2_BUCKET_NAME }}/static-home-site/ \
          --recursive \
          --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
      - name: Deploy to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          aws s3 sync ./dist s3://${{ secrets.R2_BUCKET_NAME }}/static-home-site/ \
          --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
          --no-progress
